basePath: /
definitions:
  app.pingResp:
    properties:
      status:
        type: string
    type: object
host: "127.0.0.1"
info:
  contact:
    email: bitop@spatecon.ru
    name: API Support
    url: https://vk.com/bmstu_schedule
  description: Bmstu Open IT Platform
  license:
    name: AS IS (NO WARRANTY)
  title: BITOP
  version: "1.0"
paths:
  /ping/{name}:
    get:
      description: very very friendly response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.pingResp'
      summary: Show hello text
      tags:
      - Tests
schemes:
- https
- http
swagger: "2.0"
